config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :charges

  resources :purchases, only: [:show]

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	def to_param
		uuid
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def create

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => params[:amount],
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	  purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], amount: params[:amount], 
	  	description: charge.description, currency: charge.currency, customer_id: customer.id, product_id: 1, uuid: SecureRandom.uuid)

	  redirect_to purchase

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def show
		@purchase = Purchase.find_by_uuid(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.erb
Purchase successful

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  
  <title>One Month Growth Hacking</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="content" class="container">
	    <header id="content-header">
	        <div id="price-container">
	          <span class="glyphicon glyphicon-tag"></span><span class="price">$4.99</span>
	        </div>
	        <%= image_tag('header-image.jpg', id: 'content-header-img', alt: 'Learn Growth Hacking') %>
	    </header>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/home.html.erb
  <section id="content-details" class="row clearfix">
    <article id="details-article" class="col-sm-8">
      <h1 id="article-title">Growth Hacking <span class="font-weight-light">Crash Course</span></h1>
      <h3><small>By <a href="#" data-toggle="modal" data-target="#author-modal">Mattan Griffel</a></small></h3>

      <p>A growth hacker is a rare combination: someone with the right marketing and technical skills who can come up with clever marketing hacks and also track their results.</p>

      <p>In this talk, Mattan Griffel introduces you to the concept of Growth Hacking and shares his favorite tips for getting started as a growth hacker.</p>
      <p><strong>What You'll Learn</strong></p>
      <ul class="no-indent">
          <li>What is a growth hacker?</li>
          <li>The 5 stages of the user lifecycle</li>
          <li>How to apply the Lean Marketing Framework</li>
          <li>Resources and tools you'll need to know</li>
      </ul>
    </article>
    <aside id="details-aside" class="col-sm-4">
      <%= form_tag charges_path, id:'chargeForm' do %>
        <%= hidden_field_tag 'stripeToken' %> 
        <%= hidden_field_tag 'stripeEmail' %> 
        <%= hidden_field_tag 'amount', 499 %>     
        <script src="https://checkout.stripe.com/checkout.js"></script>      
        <button id='btn-buy' type='button' class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon glyphicon-ok"></span>I want this!</button>
        
        <script type="text/javascript">
          var handler = StripeCheckout.configure({
            key: '<%= Rails.configuration.stripe[:publishable_key] %>',
            token: function(token,arg){
              document.getElementById("stripeToken").value = token.id; 
              document.getElementById("stripeEmail").value = token.email; 
              document.getElementById("chargeForm").submit();
            }
          });
          
          document.getElementById('btn-buy').addEventListener('click',function(e){         
            handler.open({
              name: 'One Month',
              description: 'Growth Hacking Crash Course ($4.99)',
              amount: document.getElementById("amount").value
            });          
          });
        </script>
      <% end %>
      
      <ul id="details-infobox" class="list-group">
        <li class="list-group-item active clearfix">DETAILS</li>
        <li class="list-group-item">You'll get one video</li>
        <li class="list-group-item clearfix">
          <span class="pull-left content-qualifier">Length</span>
          <span class="pull-right">30 minutes</span>
        </li>
      </ul>
    </aside>
  </section>
</div>
<footer id="site-footer">
Made by <a href="http://onemonth.com" target="_blank"><%= image_tag('one-month-logo.svg', id: 'one-month-footer-logo', alt: 'One Month') %></a>
</footer>

<!-- Modal -->
<div class="modal fade" id="author-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><span class="glyphicon glyphicon-user"></span>About the Teacher</h4>
      </div>
      <div class="modal-body clearfix">
            <div id="modal-left" class="pull-left">
                <p><strong>Mattan Griffel</strong></p>
                <p>Hey, I'm Mattan Griffel, co-founder of the Y Combinator backed <a href="http://www.onemonth.com" target="_blank">One Month</a> where I teach the best selling One Month Rails and One Month Growth Hacking.</p>
                <p>Why take my class? In the past I've advised companies like Pepsico, Bloomberg, GM, NYSE, and JPMorgan on growth hacking best practices. I've also spoken at New York University, Cooper Union and First Round Capital. My goal is to help you and other entrepreneurs rapidly grow your business. 
                </p>
                <p>Follow me on Twitter <a href="https://twitter.com/mattangriffel" target="_blank">@mattangriffel</a></p>
            </div>
            <div id="modal-right" class="pull-right">
              <%= image_tag('teacher-image.jpg', alt: 'Mattan Griffel') %>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/purchases/show.html.erb
<section id="content-receipt" class="clearfix">
  <div id="receipt-container">
    <div class="dotmatrix left"></div>
    <div id="receipt-content">
      <h4 id="receipt-title">Thank You!</h4>
      <p><strong>RECEIPT</strong></p>
      <div id="receipt-details" class="row clearfix">
        <div class="col-sm-8 receipt-left">
          <p><strong class="font-weight-heavy">Growth Hacking</strong><br/> <span class="font-weight-light">Crash Course</span></p>
        </div>
        <div class="col-sm-4">
          $4.99
        </div>
      </div>

      <button type="button" class="btn btn-success btn-xs">DOWNLOAD</button>
      <footer id="receipt-footer">
        <small>Your purchase is complete. We hope you enjoy it!</small>
      </footer>
    </div>
    <div class="dotmatrix right"></div>
  </div>
  <div id="receipt-shadow"></div>
</section>